### ISSUE TITLE
Issue initializing BME280

### ISSUE THREAD

**Issue by stevebus** [Azure-Samples/iot-hub-c-raspberrypi-getstartedkit#30]
I'm having issues initializing my BME280.  I'm pretty sure I've got it wired correctly.  I always get the error below:

pi@raspberrypi:~ $ sudo ~/cmake/serializer/samples/remote_monitoring/remote_monitoring
bme280_init(0)
Read 0x00 from register 0xd0
This is not a BME280. Expecting an ID register value of 0x60
It appears that no BMP280 module on Chip Enable 0 is attached. Aborting.
pi@raspberrypi:~ $

I tried this exact same BME280 chip (from Adafruit) with the bmetest.ino app test app provided by Adafruit and it works fine.  In fact, I modified that app to do a read from the 0xD0 register and got a '96' (0x60) back.   So I know the BME280 chip is fine.

Has anyone seen this issue before?  Any ideas to troubleshoot further?

also, shouldn't the 3.3v pin on the RPI connect to the Vin pin on the BME280 instead of the V0 (out) pin?  (either way doesn't fix my problem above).

**Comment by MBevil** [comment]
Steve,

I have the same issue - did you find the cause of the issue or work around?

**Comment by stevebus** [comment]
No, unfortunately not.  I was in a rush for my demo, so I switched to a DHT22 I had laying around to get over the hump.  I haven't had time to revisit it yet.  Still want to get it working, though.

**Comment by Ilias-Tsigkogiannis** [comment]
I cannot repro this problem using the latest code and configuration. Could you follow the latest instructions and verify that this is still the case?
